apiVersion: apps/v1
kind: Deployment
metadata:
  name: chesstango-epd-worker
  labels:
    app: chesstango-epd-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chesstango-epd-worker
  template:
    metadata:
      name: chesstango-epd-worker
      labels:
        app: chesstango-epd-worker
    spec:
      containers:
        - name: chesstango-epd-worker
          image: coriamauricio/epd-worker:1.4.0-SNAPSHOT
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1
            limits:
              cpu: 1
          env:
            - name: RABBIT_HOST
              value: "chesstango-rabbit-svc.default.svc.cluster.local"
      restartPolicy: Always
      